// Schemas for premium clinical anamnesis modules
// Each field: { key, label, type, options?, full?, when?(answers), help? }

export const SCHEMA_GERAL = [
  { key: "queixa_principal", label: "Queixa principal", type: "textarea", full: true },
  { key: "historico_clinico", label: "Histórico clínico", type: "textarea", full: true },
  { key: "tratamentos_anteriores", label: "Tratamentos estéticos anteriores", type: "textarea", full: true },
  { key: "doencas", label: "Doenças preexistentes", type: "chips",
    options: ["Diabetes", "Hipertensão", "Câncer", "Hipotireoidismo", "Anemia", "Distúrbios hormonais"] },
  { key: "alergias", label: "Possui alergias?", type: "select", options: ["Não", "Sim"] },
  { key: "alergias_descricao", label: "Descreva as alergias", type: "text", full: true,
    when: (a) => a.alergias === "Sim" },
  { key: "medicacoes", label: "Medicações contínuas", type: "textarea", full: true },
  { key: "cirurgias", label: "Cirurgias anteriores", type: "textarea", full: true },
  { key: "gestante", label: "Gestante / amamentando?", type: "select",
    options: ["Não", "Sim - gestante", "Sim - amamentando"] },
  { key: "tabagismo", label: "Tabagismo", type: "select", options: ["Não", "Sim"] },
  { key: "alcool", label: "Consumo de álcool", type: "select",
    options: ["Não", "Social", "Frequente"] },
  { key: "historico_familiar", label: "Histórico familiar relevante", type: "textarea", full: true },
  { key: "observacoes_clinicas", label: "Observações clínicas", type: "textarea", full: true },
];

export const SCHEMA_FACIAL = [
  { key: "tipo_pele", label: "Tipo de pele", type: "select",
    options: ["Seca", "Normal", "Mista", "Oleosa"] },
  { key: "fototipo", label: "Fototipo (Fitzpatrick)", type: "select",
    options: ["I", "II", "III", "IV", "V", "VI"] },
  { key: "oleosidade", label: "Oleosidade", type: "select",
    options: ["Baixa", "Média", "Alta"] },
  { key: "acne", label: "Acne", type: "select",
    options: ["Ausente", "Leve", "Moderada", "Severa"] },
  { key: "manchas", label: "Manchas", type: "chips",
    options: ["Melasma", "Hipercromia pós-inflamatória", "Sardas", "Hipocromia"] },
  { key: "rugas", label: "Rugas", type: "chips",
    options: ["Testa", "Glabela", "Pés de galinha", "Bigode chinês", "Marionete", "Código de barras"] },
  { key: "flacidez", label: "Flacidez", type: "select",
    options: ["Ausente", "Leve", "Moderada", "Acentuada"] },
  { key: "sensibilidade", label: "Sensibilidade", type: "select",
    options: ["Baixa", "Média", "Alta"] },
  { key: "rosacea", label: "Rosácea", type: "select", options: ["Não", "Sim"] },
  { key: "habitos_solares", label: "Exposição solar", type: "select",
    options: ["Não", "Ocasional", "Frequente", "Diária"] },
  { key: "uso_protetor", label: "Uso de protetor solar?", type: "select",
    options: ["Não", "Esporádico", "Diário"] },
  { key: "skincare_atual", label: "Rotina de skincare atual", type: "textarea", full: true },
  { key: "tratamentos_anteriores_face", label: "Tratamentos faciais anteriores", type: "textarea", full: true },
];

export const SCHEMA_CORPORAL = [
  { key: "altura", label: "Altura (cm)", type: "number" },
  { key: "peso", label: "Peso (kg)", type: "number" },
  { key: "imc", label: "IMC (calculado)", type: "text",
    help: "Preencher altura e peso (cálculo automático no relatório).",
  },
  { key: "distribuicao_gordura", label: "Distribuição de gordura", type: "select",
    options: ["Andróide", "Ginóide", "Mista"] },
  { key: "celulite_grau", label: "Grau de celulite", type: "select",
    options: ["Ausente", "Grau I", "Grau II", "Grau III", "Grau IV"] },
  { key: "regioes_celulite", label: "Regiões afetadas", type: "chips",
    options: ["Glúteos", "Coxas", "Abdômen", "Braços", "Flancos"] },
  { key: "flacidez_corporal", label: "Flacidez corporal", type: "select",
    options: ["Ausente", "Leve", "Moderada", "Acentuada"] },
  { key: "estrias", label: "Estrias", type: "chips",
    options: ["Brancas", "Vermelhas", "Roxas"] },
  { key: "gordura_localizada", label: "Gordura localizada", type: "chips",
    options: ["Abdômen", "Flancos", "Coxas", "Glúteos", "Braços", "Costas"] },
  { key: "perimetria_abdomen", label: "Perimetria abdômen (cm)", type: "number" },
  { key: "perimetria_quadril", label: "Perimetria quadril (cm)", type: "number" },
  { key: "perimetria_coxa", label: "Perimetria coxa (cm)", type: "number" },
  { key: "atividade_fisica", label: "Atividade física", type: "select",
    options: ["Sedentário", "Leve", "Moderada", "Intensa"] },
  { key: "habitos_alimentares", label: "Hábitos alimentares", type: "textarea", full: true },
];

export const SCHEMA_CAPILAR = [
  { key: "tipo_cabelo", label: "Tipo de cabelo", type: "select",
    options: ["Liso", "Ondulado", "Cacheado", "Crespo"] },
  { key: "espessura_fio", label: "Espessura do fio", type: "select",
    options: ["Fino", "Médio", "Grosso"] },
  { key: "oleosidade_couro", label: "Oleosidade do couro cabeludo", type: "select",
    options: ["Seco", "Normal", "Oleoso"] },
  { key: "porosidade", label: "Porosidade", type: "select",
    options: ["Baixa", "Média", "Alta"] },
  { key: "elasticidade", label: "Elasticidade", type: "select",
    options: ["Baixa", "Média", "Alta"] },
  { key: "queda", label: "Queda capilar", type: "select",
    options: ["Não", "Leve", "Moderada", "Acentuada"] },
  { key: "queda_padrao", label: "Padrão da queda", type: "select",
    options: ["Difusa", "Androgenética", "Areata", "Pós-parto", "Stress"],
    when: (a) => a.queda && a.queda !== "Não" },
  { key: "quimica", label: "Possui química?", type: "chips",
    options: ["Coloração", "Descoloração", "Progressiva", "Relaxamento", "Permanente"] },
  { key: "coloração_freq", label: "Frequência de coloração", type: "select",
    options: ["Nunca", "Eventual", "Mensal", "Quinzenal"] },
  { key: "doencas_couro", label: "Doenças do couro cabeludo", type: "chips",
    options: ["Caspa", "Dermatite seborreica", "Psoríase", "Foliculite"] },
  { key: "habitos_capilar", label: "Hábitos / rotina capilar", type: "textarea", full: true },
];

export const MODULE_LABELS = {
  geral: "Anamnese Geral",
  facial: "Anamnese Facial",
  corporal: "Anamnese Corporal",
  capilar: "Anamnese Capilar / Tricologia",
};
